# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://localhost:1313/"
title = "A Blog With No Name"
enableRobotsTXT = true
enableEmoji = true
theme = "PaperMod"

hasCJKLanguage = false     # has chinese/japanese/korean ?
rssLimit = 20             # Limit Entry Count to Rss file
disqusShortname = ""      # disqus_shortname
copyright = ""            # default: params.author.name ↓

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir  = true

[pagination]
  pagerSize = 5           # Number of articles displayed on the homepage

[languages.fr]
  contentDir = 'content/fr'
  disabled = false
  languageCode = 'fr'
  languageDirection = 'ltr'
  languageName = 'Français'
  title = 'A Blog With No Name'
  weight = 1
  [languages.fr.menus]
    [[languages.fr.menus.main]]
      name = 'Accueil'
      pageRef = '/'
      weight = 10
    [[languages.fr.menus.main]]
      name = 'Posts'
      pageRef = '/posts'
      weight = 20
    [[languages.fr.menus.main]]
      name = 'Tags'
      pageRef = '/tags'
      weight = 30

[languages.en]
  contentDir = 'content/en'
  disabled = false
  languageCode = 'en'
  languageDirection = 'ltr'
  languageName = 'English'
  title = 'A Blog With No Name'
  weight = 2
  [languages.en.menus]
    [[languages.en.menus.main]]
      name = 'Home'
      pageRef = '/'
      weight = 10
    [[languages.en.menus.main]]
      name = 'Posts'
      pageRef = '/posts'
      weight = 20
    [[languages.en.menus.main]]
      name = 'Tags'
      pageRef = '/tags'
      weight = 30

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  author = "Félix"
  since = "2025"
  comments = false
  ShowReadingTime = true
  ShowWordCount = true
  UseHugoToc = true
  showtoc = false
  logoTitle = "A Blog With No Name"
  keywords = ["Blog", "personal", "development", "digital garden"]
  description = "A personal blog about whatever goes through my mind."
  showMenuLanguageChooser = true
  dateFormatToUse = "2006-01-02"
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  # (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my blog"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/FRosay"

  [[params.socialIcons]]
      name = "itchio"
      url = "https://kiwi-productions.itch.io/"

  [[params.socialIcons]]
      name = "rss"
      url = "http://localhost:1313/"