# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://localhost:1313/"
title = "A Blog With No Name"
enableRobotsTXT = true
enableEmoji = true
theme = "PaperMod"

hasCJKLanguage = false     # has chinese/japanese/korean ?
rssLimit = 20             # Limit Entry Count to Rss file
disqusShortname = ""      # disqus_shortname
copyright = ""            # default: params.author.name ↓

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"
defaultContentLanguageInSubdir  = true

[pagination]
  pagerSize = 5           # Number of articles displayed on the homepage

[languages.fr]
  contentDir = 'content/fr'
  disabled = false
  languageCode = 'fr'
  languageDirection = 'ltr'
  languageName = ':fr:'
  title = 'A Blog With No Name'
  weight = 1
  [languages.fr.menus]
    [[languages.fr.menus.main]]
      name = 'Accueil'
      pageRef = '/'
      weight = 10
    [[languages.fr.menus.main]]
      name = 'Posts'
      pageRef = '/posts'
      weight = 20
    [[languages.fr.menus.main]]
      name = 'Tags'
      pageRef = '/tags'
      weight = 30
  [languages.fr.params.homeInfoParams]
    title = "Bienvenue !"
    content = """\
    Il existe aujourd'hui plus d'1,1 milliards de sites internets, et vous avez pourtant fait le choix \
    de passer un peu de votre précieux temps sur celui-ci en particulier. \r J'en suis honoré, fier, mais aussi, \
    pour être honnête, un peu inquiet. J'espère que vous apprécierez tout de même l'endroit : s'il est assez vide \
    pour le moment, je prévois vraiment d'en faire un lieu aussi *cosy* et accueillant qu'un blog - ou un \
    *jardin digital*, puisque c'est à la mode - peut l'être.\
    """

[languages.en]
  contentDir = 'content/en'
  disabled = false
  languageCode = 'en'
  languageDirection = 'ltr'
  languageName = ':en:'
  title = 'A Blog With No Name'
  weight = 2
  [languages.en.menus]
    [[languages.en.menus.main]]
      name = 'Home'
      pageRef = '/'
      weight = 10
    [[languages.en.menus.main]]
      name = 'Posts'
      pageRef = '/posts'
      weight = 20
    [[languages.en.menus.main]]
      name = 'Tags'
      pageRef = '/tags'
      weight = 30
  [languages.en.params.homeInfoParams]
    title = "Welcome!"
    content = """\
    Out of the more than 1.1 billion existing websites, you chose to spend your precious time on this shoddy little part of the Web. \
    It makes me feel honoured, proud, but honestly also a bit worried too. I hope you’ll like it here: although there’s not much at the moment, \
    I truly plan on making this place as cosy and welcoming as a digital blog - or garden, as is the trend - can be. \
    """

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  author = "Félix"
  since = "2025"
  defaultTheme = "auto"
  comments = false
  showReadingTime = true
  showWordCount = true
  useHugoToc = true
  showtoc = false
  logoTitle = "A Blog With No Name"
  keywords = ["Blog", "personal", "development", "digital garden"]
  description = "A personal blog about whatever goes through my mind."
  dateFormat = "02 January 2006"
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  # (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/FRosay"

  [[params.socialIcons]]
      name = "itchio"
      url = "https://kiwi-productions.itch.io/"

  [[params.socialIcons]]
      name = "rss"
      url = "http://localhost:1313/"